import os

DEFAULT_AWS_REGION = "us-east-1"

AWS_REGION = os.environ.get("AWS_REGION", DEFAULT_AWS_REGION)
PREDICTION_QUEUE_NAME = os.environ.get("PREDICTION_QUEUE")
MODEL_ENDPOINT_NAME = os.environ.get("MODEL_ENDPOINT_NAME")
GEOLOCATION_FN_NAME = os.environ.get("GEOLOCATION_FN_NAME")
RELIABILITY_FN_NAME = os.environ.get("RELIABILITY_FN_NAME")
MODEL_INFO_FN_NAME = os.environ.get("MODEL_INFO_FN_NAME")

SENTRY_URL = os.environ.get("SENTRY_URL")
ENVIRONMENT = os.environ.get("ENVIRONMENT")